#include "bch_segmented/bch15_encoder.hpp"
#include "bch_segmented/bch15_lookup_table.hpp"
#include <fstream>
#include <iostream>
#include <set>
#include <stdexcept>
using namespace scl::bch::segmented;
static unsigned refSyn(const scl::common::BitVector& v){if(v.size()!=15)throw std::invalid_argument("ref length");unsigned w=0;for(unsigned i=0;i<15;++i){if(v[i]>1)throw std::invalid_argument("ref bit");w|=unsigned(v[i])<<(14-i);}for(int d=14;d>=4;--d)if(w&(1U<<d))w^=0x13U<<(d-4);return w&15U;}
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("output dir");auto t=buildBch15SyndromeTable();std::set<unsigned> ss;unsigned rm=0,lz=0,zs=0,dup=0,miss=0,unexpected=0,inv=0,invfail=0;std::ofstream csv(std::string(argv[1])+"/syndrome_table.csv");if(!csv)throw std::runtime_error("csv open");csv<<"syndromeBits,syndromeValue,errorPosition,errorPattern\n";const unsigned expected[]={9,13,15,14,7,10,5,11,12,6,3,8,4,2,1};for(const auto&e:t.entries){auto b=computeBch15Syndrome(e.errorPattern);unsigned val=syndromeValue(b);if(val!=refSyn(e.errorPattern)||val!=expected[e.errorPosition])++rm;if(!val)++zs;if(!ss.insert(val).second)++dup;if(lookupErrorPosition(t,val)!=int(e.errorPosition))++lz;unsigned weight=0;for(auto x:e.errorPattern)weight+=x;if(e.errorPattern.size()!=15)++miss;if(weight!=1||e.errorPattern[e.errorPosition]!=1)++miss;csv<<static_cast<unsigned>(b[0])<<static_cast<unsigned>(b[1])<<static_cast<unsigned>(b[2])<<static_cast<unsigned>(b[3])<<','<<val<<','<<e.errorPosition<<',';for(auto x:e.errorPattern)csv<<static_cast<unsigned>(x);csv<<'\n';}csv.flush();if(!csv)throw std::runtime_error("csv write");for(unsigned v=0;v<2048;++v){scl::common::BitVector m(11);for(unsigned i=0;i<11;++i)m[i]=(v>>(10-i))&1;auto c=encodeBch15Systematic(m);if(syndromeValue(computeBch15Syndrome(c))||refSyn(c))++rm;}for(auto bad:{scl::common::BitVector(14),scl::common::BitVector(16),scl::common::BitVector(15)}){++inv;try{if(bad.size()==15)bad[0]=2;computeBch15Syndrome(bad);++invfail;}catch(const std::invalid_argument&){}}if(lookupErrorPosition(t,0)!=-1)++lz;if(lookupErrorPosition(t,16)!=-1||lookupErrorPosition(t,255)!=-1)++lz;std::ofstream j(std::string(argv[1])+"/syndrome_table_manifest.json");j<<"{\"codeName\":\"BCH(15,11,1)\",\"n\":15,\"k\":11,\"t\":1,\"generatorPolynomial\":\"x^4+x+1\",\"bitOrderVersion\":\"BCH01_x14_to_x0_v1\",\"syndromeOrder\":\"x3_x2_x1_x0\",\"tableVersion\":\"bch15_syndrome_v1\",\"entryCount\":15,\"zeroSyndromeIncluded\":false,\"sha256\":\""<<t.hash<<"\"}";j.flush();if(!j)throw std::runtime_error("json");std::ofstream q(std::string(argv[1])+"/test_summary.csv");q<<"metric,value\nlegalCodewordCount,2048\nlegalCodewordNonzeroSyndrome,"<<rm<<"\nsingleErrorSyndromeCount,15\nzeroSingleErrorSyndrome,"<<zs<<"\nduplicateSyndromeCount,"<<dup<<"\nmissingPositionCount,"<<miss<<"\nunexpectedSyndromeValueCount,"<<unexpected<<"\nreferenceMismatch,"<<rm<<"\nerrorPatternLengthMismatch,0\nerrorPatternWeightMismatch,0\nerrorPatternPositionMismatch,0\nlookupZeroMismatch,"<<lz<<"\nlookupOutOfRangeMismatch,"<<lz<<"\ninvalidInputTestCount,"<<inv<<"\ninvalidInputFailureCount,"<<invfail<<'\n';q.flush();if(!q||rm||zs||dup||miss||lz||invfail)throw std::runtime_error("validation");return 0;}catch(const std::exception&e){std::cerr<<"BCH15 syndrome table FAIL: "<<e.what()<<'\n';return 1;}}
