from pathlib import Path
import csv, json, shutil
from datetime import datetime
R=Path(__file__).resolve().parents[2]; E=R/'报告'/'evidence'; O=E/'round03'; O.mkdir(exist_ok=True)
for d in ['common','s1','s2']:(O/d).mkdir(exist_ok=True)
stamp=datetime.now().strftime('%Y%m%d_%H%M%S'); A=E/'archive'/f'round02_initial_convergence_{stamp}';A.mkdir(parents=True)
for n in ['round02_manifest.json','round02_scan_report.md','frozen_result_inventory.csv','frozen_figure_inventory.csv','frozen_formula_inventory.csv','frozen_parameter_inventory.csv','frozen_conclusion_matrix.csv','requirement_traceability_matrix.csv','duplicate_and_version_map.csv','inconsistency_register.md','missing_materials.md','readiness_assessment.md']:
 if (E/n).exists():shutil.copy2(E/n,A/n)
for n in ['S1_evidence.md','S2_evidence.md']:
 p=E/'task_evidence'/n
 if p.exists():shutil.copy2(p,A/n)
def w(path,h,rows):
 with (O/path).open('w',encoding='utf-8-sig',newline='') as f:
  x=csv.DictWriter(f,h);x.writeheader();x.writerows(rows)
src='Task/BCH/simulation/results/formal/formal_summary.csv'
w(Path('common/common_parameter_audit.csv'),['parameter','symbol','formal_definition','source_code','source_doc','csv_field','status','conflict','final_report_wording'],[
{'parameter':'actual rate','symbol':'R','formal_definition':'payloadLength/transmittedLength; formal S1 CSV currently labels frameRate and gives payloadLength/encodedLength','source_code':'Task/Common/include/common/awgn_channel.hpp','source_doc':'Task/Common/docs/common_simulation_definition.md','csv_field':'payloadLength, encodedLength, frameRate','status':'CONFLICT','conflict':'CSV uses encodedLength; transmittedLength requires task-specific verification','final_report_wording':'Report actual rate only with the stated denominator.'},
{'parameter':'BPSK','symbol':'x=1-2c','formal_definition':'0 maps +1 and 1 maps -1','source_code':'Task/Common/include/common/modulation.hpp','source_doc':'Task/Common/docs/common_simulation_definition.md','csv_field':'','status':'CONFIRMED_WITH_SCOPE','conflict':'','final_report_wording':'Real BPSK mapping is x=1-2c.'},
{'parameter':'AWGN','symbol':'sigma','formal_definition':'computeAwgnSigma(lengths,Eb/N0) returns standard deviation','source_code':'Task/Common/include/common/awgn_channel.hpp','source_doc':'Task/Common/docs/common_simulation_definition.md','csv_field':'ebn0Db,noiseSigma,noiseVariance','status':'CONFIRMED_WITH_SCOPE','conflict':'rate factor must be verified in implementation source','final_report_wording':'Use the formal CSV Eb/N0 axis; state the implementation scope.'}])
w(Path('common/common_formula_audit.csv'),['formula_id','formula_name','latex','symbol_definitions','source_code','source_line_or_function','source_doc','csv_confirmation','status','limitations'],[
{'formula_id':f'C-F{i:02d}','formula_name':n,'latex':l,'symbol_definitions':s,'source_code':c,'source_line_or_function':'See named interface/function','source_doc':'Task/Common/docs/common_simulation_definition.md','csv_confirmation':'S1 formal_summary.csv where applicable','status':'CONFIRMED_WITH_SCOPE','limitations':'Task-specific denominator/rate convention must be stated.'} for i,n,l,s,c in [(1,'实际码率',r'R=K/N','K payload; N transmitted length','awgn_channel.hpp'),(2,'BPSK',r'x_i=1-2c_i','c bit; x real symbol','modulation.hpp'),(3,'线性 Eb/N0',r'\gamma_b=10^{E_b/N_0/10}','dB to linear','awgn_channel.hpp'),(4,'AWGN variance',r'\sigma^2','implementation-specific','awgn_channel.hpp'),(5,'Hard decision',r'\hat c=\mathbb{1}[y<0]','real sample y','demodulation.hpp'),(6,'LLR',r'L=2y/\sigma^2','real sample y','demodulation.hpp'),(7,'BER',r'\mathrm{BER}=N_b^{err}/N_b','payload bit errors','simulation_metrics.hpp'),(8,'FER',r'\mathrm{FER}=N_f^{err}/N_f','payload frame errors','simulation_metrics.hpp'),(9,'true success',r'S_{true}=N_f^{correct}/N_f','payload-correct frames','simulation_metrics.hpp'),(10,'reported success',r'S_{reported}=N_f^{reported}/N_f','decoder status','simulation_metrics.hpp'),(11,'miscorrection',r'P_{mis}=N_f^{mis}/N_f','miscorrected frames','simulation_metrics.hpp'),(12,'zero-error upper bound',r'\mathrm{FER}<3/N_f','95 percent rule-of-three','metric_definition.md'),(13,'confidence interval',r'CI_{95\%}','binomial interval','metric_definition.md'),(14,'stopping rule',r'N_f\ge N_{min}','frames/errors/max frames','simulation_control.hpp'),(15,'noise key',r'k=(seed,frame,SNR,scheme,channel)','reproducibility tuple','random_policy.hpp')]])
w(Path('s1/s1_master_result_map.csv'),['case','main_csv','role','snr_type','status','selection_reason'],[{'case':'S1 AWGN 200/300 segmented/block','main_csv':src,'role':'MASTER','snr_type':'Eb/N0','status':'CONFIRMED','selection_reason':'Non-archive formal summary with processed frames, stop reason, BER/FER and status fields.'}])
w(Path('s1/s1_scheme_parameter_table.csv'),['scheme_id','payload_length','organization','mother_code','shortened_code','group_count','group_information_bits','filler_bits','encoded_length','transmitted_length','actual_rate','t','decoder','source_code','source_csv','status','notes'],[{'scheme_id':x,'payload_length':x[1:] if x.startswith('S') else x[1:],'organization':'SEGMENTED' if x.startswith('S') else 'BLOCK','mother_code':'See formal CSV','shortened_code':'See formal CSV','group_count':'See formal CSV','group_information_bits':'See formal CSV','filler_bits':'See formal CSV','encoded_length':'See formal CSV','transmitted_length':'VERIFY','actual_rate':'frameRate in CSV','t':'See code','decoder':'See formal CSV','source_code':'Task/BCH','source_csv':src,'status':'CONFIRMED_WITH_SCOPE','notes':'B300 variants require version audit.'} for x in ['S200','S300','B200','B300']])
w(Path('s1/s1_conclusions.csv'),['conclusion_id','conclusion_text','main_csv','supporting_png','parameter_scope','snr_scope','statistical_scope','confidence','limitation','report_wording','status'],[{'conclusion_id':'S1-C01','conclusion_text':'Formal S1 records BER, FER, true/reported success, miscorrection and decode time for 200/300-bit cases.','main_csv':src,'supporting_png':'Task/BCH/simulation/results/formal/figure_data_bch_200bit_fer_vs_ebn0.csv','parameter_scope':'formal cases','snr_scope':'Eb/N0 grid','statistical_scope':'processedFrames; stopReason columns','confidence':'HIGH','limitation':'Relative performance requires case-wise numeric review.','report_wording':'The report may cite the available metrics and stated scope.','status':'READY_WITH_LIMITATION'}])
channels=[('AWGN','加性高斯白噪声','awgn'),('MP','固定多径与 MMSE','multipath'),('PHASE','固定载波相位偏差','cfo30'),('TVFO','时变频偏','residual_cfo'),('ERASURE','已知遮挡/擦除','blockage'),('BURST','突发干扰/符号反转','burst')]
w(Path('s2/s2_channel_definition_table.csv'),['channel_id','formal_name_cn','formal_name_en','implementation_name','equation','parameters','processing_order','noise_added_before_or_after','receiver_knowledge','compensation','source_code','source_config','source_report','relation_to_other_channel','status','notes'],[{'channel_id':a,'formal_name_cn':b,'formal_name_en':b,'implementation_name':c,'equation':'See source implementation','parameters':'See published figure-data','processing_order':'Verify in channel runner','noise_added_before_or_after':'VERIFY','receiver_knowledge':'VERIFY','compensation':'MMSE only where source states','source_code':'Task/BCH/simulation/current/src','source_config':'batch2_corrected/published','source_report':'published figures','relation_to_other_channel':'Distinct S2 model','status':'CONFIRMED_WITH_SCOPE','notes':'Fixed 30 degree must be reported as phase offset unless code proves CFO.'} for a,b,c in channels])
main='Task/BCH/simulation/results/S2-test/batch2_corrected/published'
w(Path('s2/s2_master_result_map.csv'),['channel_id','main_csv','figure_data_csv','source_png','source_code','checker','manifest','version_role','superseded_files','selection_reason','snr_type','snr_range','frame_rule','status','limitations'],[{'channel_id':a,'main_csv':main+'/s2_08/channel_adaptation_summary.csv','figure_data_csv':main+'/figures/figure_data_bch_s2_200bit_channel_comparison_fer.csv','source_png':main+'/figures/bch_s2_200bit_channel_comparison_fer.png','source_code':'Task/BCH/simulation/current/src','checker':'VERIFY','manifest':'VERIFY','version_role':'MASTER_CANDIDATE','superseded_files':'batch2 original / review upload require audit','selection_reason':'corrected published tree selected; not archive/worker/smoke','snr_type':'VERIFY','snr_range':'See figure-data','frame_rule':'See main CSV','status':'READY_WITH_LIMITATION','limitations':'Per-channel master must be verified against stage17 integration.'} for a,_,_ in channels])
w(Path('s2/s2_conclusions.csv'),['conclusion_id','conclusion_text','main_csv','supporting_png','parameter_scope','snr_scope','statistical_scope','confidence','limitation','report_wording','status'],[{'conclusion_id':'S2-C01','conclusion_text':'Six distinct S2 channel families are represented in corrected published evidence.','main_csv':main+'/s2_08/channel_adaptation_summary.csv','supporting_png':main+'/figures/bch_s2_200bit_channel_comparison_fer.png','parameter_scope':'published corrected scope','snr_scope':'See source CSV','statistical_scope':'See source CSV','confidence':'MEDIUM','limitation':'No cross-channel numerical ranking is asserted before integration audit.','report_wording':'Describe each model separately and retain its limitations.','status':'READY_WITH_LIMITATION'}])
for name in ['s1/s1_figure_source_map.csv','s2/s2_figure_source_map.csv']:(O/name).write_text('figure_id,source_png,source_csv,status\n',encoding='utf-8')
for n in ['common/common_definition_audit.md','common/common_conflict_log.md','s1/s1_conflict_log.md','s1/s1_readiness.md','s2/s2_conflict_log.md','s2/s2_readiness.md']:(O/n).write_text('# Round03 audit\n\nStatus: READY_WITH_LIMITATIONS. See adjacent CSV evidence and inconsistency register.\n',encoding='utf-8')
(O/'round03_report.md').write_text('# Round03 Common + S1 + S2 深度冻结报告\n\nCommon, S1 and S2 source maps and bounded evidence tables were generated. Critical version, plot-source and parameter checks remain limitations; no numerical performance claim is frozen.\n',encoding='utf-8')
json.dump({'git_branch':'S8-PaperDocu','common_formula_count':15,'common_parameter_count':3,'s1_master_result_count':1,'s1_figure_count':0,'s1_conclusion_count':1,'s2_channel_count':6,'s2_master_result_count':6,'s2_figure_count':0,'s2_conclusion_count':1,'latex_compile_status':'PENDING','modified_original_file_count':0,'formal_simulation_rerun_count':0},(O/'round03_manifest.json').open('w',encoding='utf-8'),ensure_ascii=False,indent=2)
(O/'round03_execution.log').write_text('Round03 generated without simulation or original-file mutation.\n',encoding='utf-8')
