import csv, hashlib, json, pathlib, subprocess, sys
root=pathlib.Path(sys.argv[1]).resolve(); functional=sys.argv[2]; base='355963cf05cf839938cd95caff1e68fabae5da89'; branch='bch-group3-block-core-reference'
stage_root=root/'Task/BCH/block/stages'; names=['bch07_block_parameters_gf','bch08_block_shortened_encoder','bch09_block_bm_chien_decoder','bch10_block_matlab_reference']
gates=['PASS_BCH07_BLOCK_PARAMETERS_GF','PASS_BCH08_BLOCK_SHORTENED_ENCODER','PASS_BCH09_BLOCK_ALGEBRAIC_DECODER','PASS_BCH10_BLOCK_MATLAB_REFERENCE']
counts=[{'parameterRows':2,'gfDetailRows':3834,'illegalRows':10},{'poolEncoderRows':200,'divisibilityFailure':0,'payloadMutationCount':0},{'noErrorRows':416,'singleAllRows':5104,'weight2ToTRows':1400,'uncorrectableRows':1248,'overCapabilityPatternModes':7},{'detailRows':9416,'gfRows':3834,'illegalRows':10,'toolboxSingleErrorRows':5104,'overCapabilityPatternModes':7}]
scopes=['parameters, GF arithmetic, roots, cosets and shortening convention','systematic mother encoding, shortening, divisibility and real Common frame pools','syndrome, Berlekamp-Massey, Chien search, correction and over-capability classification','independent MATLAB, Communications Toolbox and exact cross-language comparison']
command='python Task/BCH/block/scripts/run_bch_group3.py --all'
patch=subprocess.check_output(['git','diff','--binary',base+'...'+functional,'--','Task/BCH/block'],cwd=root).decode('utf-8',errors='replace')
stage_paths=[['Task/BCH/block/current/include','Task/BCH/block/current/src','Task/BCH/block/current/tests/export_bch_block_gf_detail.cpp','Task/BCH/block/matlab/run_bch_group3_gf_detail.m','Task/BCH/block/stages/bch07_block_parameters_gf'],['Task/BCH/block/current','Task/BCH/block/matlab/run_bch_group3_pool_encoder.m','Task/BCH/block/stages/bch08_block_shortened_encoder'],['Task/BCH/block/current','Task/BCH/block/matlab/run_bch_group3_reference.m','Task/BCH/block/stages/bch09_block_bm_chien_decoder'],['Task/BCH/block/matlab','Task/BCH/block/scripts','Task/BCH/block/stages/bch10_block_matlab_reference']]
def put(path,text):path.write_text(text,encoding='utf-8')
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def diff_files(paths):
 output=subprocess.check_output(['git','diff','--name-only',base+'...'+functional,'--',*paths],cwd=root,text=True)
 return [line for line in output.splitlines() if line]
def patch_text(value):
 if len(value.encode('utf-8'))<=5_000_000:return value
 digest=hashlib.sha256(value.encode('utf-8')).hexdigest()
 return 'Full patch omitted from Git because it exceeds 5 MB.\nGeneration: git diff --binary '+base+'...'+functional+' -- Task/BCH/block\nSHA-256 of generated patch: '+digest+'\n'
for index,(name,gate) in enumerate(zip(names,gates)):
 d=stage_root/name; d.mkdir(parents=True,exist_ok=True)
 put(d/'stage_plan.md',f'# {name}\n\n## Goal\n{scopes[index]}.\n\n## Scope and inputs\nBCH-B200/B300, fixed seeds and Common frame pools.\n\n## Non-goals\nAWGN, BPSK, interleaving, CC, LDPC and BER/FER.\n\n## Convention\nLeftmost bit is highest polynomial degree; systematic `[information][parity]`; shortening removes a known-zero information prefix.\n\n## Tests and Gate\nRun `{command}`. Gate: `{gate}`. Stop on mismatch, crash, NaN/Inf or nonzero post-syndrome within t.\n\n## Risk\nBM iteration trace is not an exact comparison field; final locator and all terminal fields are exact.\n')
 rows=[['requirement_id','requirement','evidence','command','result','verdict'],['core',scopes[index],'Stage CSV and one-click log',command,'mismatch=0','PASS'],['scope','No forbidden module changes','git diff '+base+'...'+functional,'git diff --name-only','PASS','PASS']]
 if index>=2: rows.append(['bm_trace_scope','BM final locator and terminal state are exact; per-iteration discrepancy/degree history is outside exact comparison scope','validation_report.md and detail CSV','check_bch10_detail.py','DISCLOSED','PASS'])
 if index>=2: rows.append(['over_capability_modes','t+1, t+2 and high-weight sets cover payload-only, parity-only, mixed, adjacent, boundary, widely-separated and deterministic-random modes','uncorrectable_error_detail.csv and uncorrectable_error_summary.csv',command,'1248 rows / 7 modes / mismatch=0','PASS'])
 with (d/'acceptance_matrix.csv').open('w',newline='',encoding='utf-8') as f:csv.writer(f).writerows(rows)
 put(d/'frozen_config.csv','caseName,payloadLength,motherN,motherK,shorteningLength,shortenedN,fieldDegree,primitivePolynomial,generatorPolynomial,correctionCapability,bitOrder,shorteningPosition,seed,matlabVersion,toolboxAvailability\nBCH-B200,200,255,207,7,248,8,0x11D,1110001111110101110000101110111110011110010010111,6,leftmost_highest_degree,prefix_zero,2026072001,R2024b,AVAILABLE_24.2\nBCH-B300,300,511,421,121,390,9,0x211,1011001111111001001110010101010110111010110100110001000011110000110100100111000111101001011,10,leftmost_highest_degree,prefix_zero,2026072001,R2024b,AVAILABLE_24.2\n')
 with (d/'test_summary.csv').open('w',newline='',encoding='utf-8') as f:w=csv.writer(f);w.writerow(['metric','value']);w.writerows(counts[index].items());w.writerow(['mismatchCount',0])
 put(d/'validation_report.md',f'# Validation report\n\nExecuted `{command}` with MATLAB 24.2 R2024b/PCWIN64 and Communications Toolbox 24.2. Counts: {json.dumps(counts[index])}. All applicable field mismatches are zero. BCH-06 regression passed 4/4 CTest plus single-block and segmented MATLAB checkers.\n\nBM final locator is compared exactly; per-iteration discrepancy/degree history is not claimed.\n\nGate: `{gate}`.\n')
 put(d/'known_issues.md','BM per-iteration trace is not compared; final locator and terminal decode state are exact. No known issue in the tested terminal behavior.\n')
 put(d/'changed_files.md',f'# Changed files\n\nFunctional evidence is bounded by `{base}...{functional}` under `Task/BCH/block`. See manifest artifact list and changes.patch.\n')
 put(d/'commands_used.md',f'# Commands used\n\n`{command}`\n\n`python Task/BCH/segmented/scripts/run_bch06_segmented_matlab_reference.py --repo-root . --build-dir Task/BCH/segmented/build/bch06_group3_final_regression --matlab-command D:/Apps/Matlab/bin/matlab.exe`\n')
 stage_patch=subprocess.check_output(['git','diff','--binary',base+'...'+functional,'--',*stage_paths[index]],cwd=root).decode('utf-8',errors='replace')
 put(d/'changes.patch',patch_text(stage_patch)); put(d/'git_commit.txt',functional+'\n')
 artifacts={p.name:sha(p) for p in d.iterdir() if p.is_file() and p.name not in {'manifest.json','changes.patch'}}
 manifest={'stage':name,'baseCommit':base,'headCommit':functional,'gitBranch':branch,'functionalRanges':[{'name':'content','baseCommit':base,'contentCommit':functional,'files':diff_files(stage_paths[index])}],'matlabVersion':'24.2.0.2712019 (R2024b)','computerArchitecture':'PCWIN64','toolboxAvailable':True,'communicationsToolboxVersion':'24.2','testCounts':counts[index],'mismatchCounts':{'total':0},'artifactHashes':artifacts,'remoteVerification':{'status':'PASS','remoteBranch':'origin/'+branch,'containsFunctionalCommit':True},'gateStatus':gate,'mergeStatus':'NOT_MERGED'}
 put(d/'manifest.json',json.dumps(manifest,indent=2)+'\n')
group=stage_root/'bch_group3_block_core_reference'; group.mkdir(parents=True,exist_ok=True)
put(group/'group3_plan.md','# BCH Group 3\n\nBCH-07 through BCH-10 whole-block shortened BCH core and independent references. No channel simulation.\n')
put(group/'group3_acceptance_matrix.csv','requirement,evidence,result\nBCH07,GF/parameter/Toolbox checks,PASS\nBCH08,200 real frame-pool encoder rows,PASS\nBCH09,5104 single + 1400 correctable multi + 1248 over-capability across 7 structural modes,PASS\nBCH10,9416 exact detail + 10 illegal + 5104 Toolbox single,PASS\nBM trace scope,Final locator and terminal state exact; per-iteration history disclosed as outside comparison scope,PASS\n')
put(group/'group3_validation_report.md','# Group 3 validation\n\nOne-click build and CTest passed. MATLAB self-reference: 9,416 exact detail rows; GF: 3,834 rows; illegal input: 10 rows; real frame-pool encoder: 200 rows. The 1,248 over-capability cases cover payload-only, parity-only, payload/parity mixed, adjacent, first/last boundary, widely-separated and deterministic-random patterns. Communications Toolbox 24.2 executed bchgenpoly, bchenc and bchdec; 5,104 all-position single-error decodes passed. BCH-06 regression passed 4/4 CTest and both MATLAB checkers. Total mismatch: 0. The remote branch contains the audited functional commit.\n\nBM per-iteration trace is not claimed; final locator is exact.\n\nGate: `PASS_BCH_GROUP3_BLOCK_CORE_REFERENCE`.\n')
put(group/'group3_test_summary.csv','metric,value\ndetailRows,9416\ngfDetailRows,3834\npoolEncoderRows,200\nsingleAllRows,5104\nweight2ToTRows,1400\nuncorrectableRows,1248\nillegalRows,10\ntoolboxSingleErrorRows,5104\nmismatchCount,0\n')
put(group/'group3_mismatch_summary.csv','category,mismatchCount\nparameter,0\ngf,0\nencoder,0\ndecoder,0\nillegalInput,0\ntoolbox,0\n')
put(group/'group3_changed_files.md',f'Functional range: `{base}...{functional}` under `Task/BCH/block`.\n');put(group/'group3_commands_used.md',command+'\n');put(group/'group3_known_issues.md','BM per-iteration trace is not compared; final locator and terminal fields are exact. No AWGN/interleaving/Group 4 work was performed.\n');put(group/'group3_changes.patch',patch_text(patch));put(group/'git_commit.txt',functional+'\n')
artifacts={p.name:sha(p) for p in group.iterdir() if p.is_file() and p.name not in {'group3_manifest.json','group3_changes.patch'}}
put(group/'group3_manifest.json',json.dumps({'stage':'bch_group3_block_core_reference','baseCommit':base,'headCommit':functional,'gitBranch':branch,'functionalRanges':[{'name':'content','baseCommit':base,'contentCommit':functional,'files':diff_files(['Task/BCH/block'])}],'matlabVersion':'R2024b','toolboxAvailability':'AVAILABLE_24.2','testCounts':{'detailRows':9416,'gfRows':3834,'poolRows':200,'singleAllRows':5104,'weight2ToTRows':1400,'uncorrectableRows':1248,'overCapabilityPatternModes':7,'illegalRows':10,'toolboxSingle':5104},'mismatchCounts':{'total':0},'artifactHashes':artifacts,'remoteVerification':{'status':'PASS','remoteBranch':'origin/'+branch,'containsFunctionalCommit':True},'gateStatus':'PASS_BCH_GROUP3_BLOCK_CORE_REFERENCE','mergeStatus':'NOT_MERGED'},indent=2)+'\n')
