#include "bch_block/bch_block.hpp"
#include <fstream>
#include <iostream>
namespace { using namespace scl::bch::block; using scl::common::BitVector;
BitVector payloadFor(std::size_t n,unsigned p){BitVector b(n);for(std::size_t i=0;i<n;++i)b[i]=p==0?0U:(p==1?1U:(p==2?i%2U:(p==3?(i+1U)%2U:static_cast<unsigned>(((i*37U+p*19U+11U)%101U)<50U))));return b;}
std::string ns(const std::vector<Gf2m::Element>& v){std::string s;for(auto x:v){if(!s.empty())s+=':';s+=std::to_string(x);}return s;} std::string ps(const std::vector<std::size_t>& v){std::string s;for(auto x:v){if(!s.empty())s+=':';s+=std::to_string(x);}return s;}
void inject(BitVector& r,unsigned weight,unsigned seed,std::size_t payloadLength){for(unsigned j=0;j<weight;++j){const std::size_t mode=seed%7U,parityLength=r.size()-payloadLength;std::size_t p=0;if(mode==0)p=(seed+j*17U)%payloadLength;else if(mode==1)p=payloadLength+(seed+j*7U)%parityLength;else if(mode==2)p=j%2U==0?(seed+(j/2U)*17U)%payloadLength:payloadLength+(seed+(j/2U)*7U)%parityLength;else if(mode==3)p=(seed+j)%r.size();else if(mode==4)p=j%2U==0?j/2U:r.size()-1U-j/2U;else if(mode==5)p=(seed+j*53U)%r.size();else p=(seed*37U+j*29U+7U)%r.size();r[p]^=1U;}}
void row(std::ofstream& o,const BlockBchProfile&p,unsigned pat,const std::string& kind,const BitVector& payload,const EncodeResult&e,BitVector r){const auto d=decodeShortened(p,r);const bool ok=d.payload==payload,good=d.status==DecodeStatus::NoError||d.status==DecodeStatus::Corrected;o<<p.caseName<<','<<pat<<','<<kind<<','<<bitsToString(payload)<<','<<bitsToString(e.motherCodeword)<<','<<bitsToString(e.shortenedCodeword)<<','<<bitsToString(r)<<','<<ns(d.syndromes)<<','<<d.allZeroSyndrome<<','<<d.nonzeroSyndromeCount<<','<<ns(d.locatorPolynomial)<<','<<d.locatorDegree<<','<<ps(d.motherErrorPositions)<<','<<ps(d.shortenedErrorPositions)<<','<<d.rootsInShortenedPrefix<<','<<bitsToString(d.correctedShortenedCodeword)<<','<<bitsToString(d.payload)<<','<<ns(d.postSyndromes)<<','<<d.postSyndromeZero<<','<<d.bmIterationCount<<','<<d.failureReason<<','<<statusName(d.status)<<','<<ok<<','<<good<<','<<(good&&!ok)<<'\n';}
}
int main(int argc,char**argv){if(argc!=2)return 2;std::ofstream o(argv[1]);if(!o)return 3;o<<"caseName,pattern,errorKind,payload,motherCodeword,shortenedCodeword,received,syndromes,allZeroSyndrome,nonzeroSyndromeCount,locator,locatorDegree,rootPositions,shortenedErrorPositions,rootsInShortenedPrefix,correctedShortened,decodedPayload,postSyndromes,postSyndromeZero,bmIterationCount,failureReason,status,truePayloadRecovered,reportedSuccess,miscorrected\n";for(const auto&p:{makeB200Profile(),makeB300Profile()}){for(unsigned pat=0;pat<208;++pat){auto m=payloadFor(p.payloadLength,pat);auto e=encodeShortened(p,m);for(unsigned k=0;k<7;++k){auto r=e.shortenedCodeword;std::string n="NONE";if(k==1){r[0]^=1;n="FIRST";}else if(k==2){r.back()^=1;n="LAST";}else if(k){unsigned w=k==3?p.correctionCapability:(k==4?p.correctionCapability+1U:(k==5?p.correctionCapability+2U:p.correctionCapability+5U));n=k==3?"T":(k==4?"T_PLUS_1":(k==5?"T_PLUS_2":"HIGH_WEIGHT"));inject(r,w,pat,p.payloadLength);}row(o,p,pat,n,m,e,r);}}for(unsigned pat=0;pat<8;++pat){auto m=payloadFor(p.payloadLength,pat);auto e=encodeShortened(p,m);for(std::size_t x=0;x<e.shortenedCodeword.size();++x){auto r=e.shortenedCodeword;r[x]^=1U;row(o,p,pat,"SINGLE_ALL",m,e,r);}}for(unsigned w=2;w<=p.correctionCapability;++w)for(unsigned pat=0;pat<100;++pat){auto m=payloadFor(p.payloadLength,pat+1000U+w*100U);auto e=encodeShortened(p,m);auto r=e.shortenedCodeword;inject(r,w,pat+w*1000U,p.payloadLength);row(o,p,pat,"WEIGHT_"+std::to_string(w),m,e,r);}}}
